name: mink
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cudatoolkit=11.6.0
  - pytorch-cuda=11.6
  - torchaudio==0.13.1
  - torchvision==0.14.1
  - openblas-devel
  - conda-forge::pybind11
  - ld_impl_linux-64
  - iopath
  - pytorch3d
  - cuda-version[version='>=11.4,<=11.8']
  - libcuvs=24.12
  - cmake=3.26.4
